# Mount Google Drive dan Menginstal Library

In [ ]:
#mounting google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install Textblob

Requirement already satisfied: Textblob in /usr/local/lib/python3.10/dist-packages (0.17.1)
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.10/dist-packages (from Textblob) (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->Textblob) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->Textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->Textblob) (2024.5.15)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->Textblob) (4.66.4)

In [ ]:
from textblob import TextBlob

In [ ]:
import pandas as pd

# Memuat dan Menerjemahkan Data

In [ ]:
data_path = '/content/drive/MyDrive/DataFix/SastrawiProssedSeabank.csv'

In [ ]:
!pip3 install googletrans==3.1.0a0

Collecting googletrans==3.1.0a0
  Downloading googletrans-3.1.0a0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting httpx==0.13.3 (from googletrans==3.1.0a0)
  Downloading httpx-0.13.3-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (2024.6.2)
Collecting hstspreload (from httpx==0.13.3->googletrans==3.1.0a0)
  Downloading hstspreload-2024.6.1-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 18.5 MB/s eta 0:00:00
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (1.3.1)
Collecting chardet==3.* (from httpx==0.13.3->googletrans==3.1.0a0)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 8.5 MB/s eta 0:00:00
Collecting idna==2.* (from httpx==0.13.3->googletrans==3.1.0a0)
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 7.0 MB/s eta 0:00:00
Collecting rfc3986<2,>=1.3 (from httpx==0.13.3->googletrans==3.1.0a0)
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Collecting httpcore==0.9.* (from httpx==0.13.3->googletrans==3.1.0a0)
  Downloading httpcore-0.9.1-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 5.2 MB/s eta 0:00:00
Collecting h11<0.10,>=0.8 (from httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0)
  Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 3.9 MB/s eta 0:00:00
Collecting h2==3.* (from httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0)
  Downloading h2-3.2.0-py2.py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 5.2 MB/s eta 0:00:00
Collecting hyperframe<6,>=5.2.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0)
  Downloading hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Collecting hpack<4,>=3.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0)
  Downloading hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Building wheels for collected packages: googletrans
  Building wheel for googletrans (setup.py) ... done
  Created wheel for googletrans: filename=googletrans-3.1.0a0-py3-none-any.whl size=16353 sha256=63a2bf32f7a0bf482b225281aca1abb0eaf3452ceafc42ead329202d24e2ffe9
  Stored in directory: /root/.cache/pip/wheels/50/5d/3c/8477d0af4ca2b8b1308812c09f1930863caeebc762fe265a95
Successfully built googletrans
Installing collected packages: rfc3986, hyperframe, hpack, h11, chardet, idna, hstspreload, h2, httpcore, httpx, googletrans
  Attempting uninstall: chardet
    Found existing installation: chardet 5.2.0
    Uninstalling chardet-5.2.0:
      Successfully uninstalled chardet-5.2.0
  Attempting uninstall: idna
    Found existing installation: idna 3.7
    Uninstalling idna-3.7:
      Successfully uninstalled idna-3.7
Successfully installed chardet-3.0.4 googletrans-3.1.0a0 h11-0.9.0 h2-3.2.0 hpack-3.0.0 hstspreload-2024.6.1 httpcore-0.9.1 httpx-0.13.3 hyperframe-5.2.0 idna-2.10 rfc3986-1.5.0

In [ ]:
# Importing library yang dibutuhkan
import googletrans
from googletrans import Translator

In [ ]:
data = pd.read_csv(data_path)
data.head()

                                             content
0                                                NaN
1                                                top
2           aplikasi ak penyandang disabilitas netra
3                                             mantap
4  terbaik kepuasan ya pengguna nyaselain manfaat...

In [ ]:
translator = Translator()
translations = {}
for column in data.columns:
    # Unique elements of the column
    unique_elements = data[column].unique()
    for element in unique_elements:
        # Adding all the translations to a dictionary (translations)
        translations[element] = translator.translate(element).text
translations

{nan: 'in',
 'top': 'top',
 'aplikasi ak penyandang disabilitas netra': 'application for children with visual disabilities',
 'mantap': 'solid',
 'terbaik kepuasan ya pengguna nyaselain manfaat dapatkan bertransaksi aplikasi bagus ya memiliki manfaat mudah membeli pulsa membayar tagihan listrikpdam dll aplikasi nya membantu ya berkat aplikasi kemudahan fitur fitur dimiliki aplikasi kawan': "The best user satisfaction, apart from the benefits of getting transactions, the application is good, yes it has the benefit of easily buying credit, paying electricity bills, water supply, etc. the application is helpful, thanks to the application's ease of features, friends' application.",
 'suka buka rekening trasfer lancar kendala pembaharuan kasih membingungkan pokoknya bagus de semoga maju sukses': "I like opening a transfer account smoothly, but the problem with renewal is confusing, but it's good, good luck moving forward",
 'senang kalo saldonya bnyak': "I'm happy if I have a lot of balance",
 'toppppp': 'toppppp',
 'membantu': 'help',
 'cepat mudah': 'fast easy',
 'goks': 'gok',
 'pokoknya joss': 'basically joss',
 'suka': 'criticism',
 'baguss': 'nice',
 'praktis dn transfer free biaya admin semoga kedepannya terima kasih': 'Practical and transfers are free of admin fees. Hopefully in the future, thank you',
 'bagus membantu tranfer berguna semoga berkembang': 'good help, useful transfer, hopefully it will develop',
 'bfua': 'bfua',
 'sempurna banget ya alat transfer kesesama bank digital yamenurut aplikasi bagus ya tinggal ditambah menu pelengkap biar sempurna utc memudahkan aplikasi nya jaringan stabil prose transaksi cepat menjadikan aplikasi aplikasi nyaaplikasi pa transaksi ya': "It's really perfect, a transfer tool between digital banks, according to the application, it's good, just add a complementary menu to make it perfect. UTC makes the application easy, the network is stable, the transaction process is fast, making the application a good transaction application, OK?",
 'oke bangeeet': 'okay really',
 'oke': 'limit',
 'tambahkan fitur konfirmasi pembayaran finger print pin ribet ketik pin konfirmasi pembayaran transfer': "add the finger print pin payment confirmation feature. It's complicated to type the transfer payment confirmation pin",
 'asyikk': 'asyikk',
 'bagus': 'Good',
 'good': 'good',
 'bintang yg bicara': 'talking star',
 'penggunaan mudah bermanfaat bebas biaya tf': 'easy to use, useful, free of charge tf',
 'okeee': 'okay',
 'mudah murah': 'easy cheap',
 'transfer e wallet bank pake gratisseabank top': 'Bank e-wallet transfer using Seabank Top for free',
 'keren': 'keren',
 'puas penggunaan nya': 'satisfied with its use',
 'asik mantap': 'cool cool',
 'perbaiki amanan nya': 'improve security',
 'jempol': 'thumb',
 'kemudahan aplikasi ponsel ya aplikasi nya bermanfaat kepuasan yafitur fitur nya lengkap memudahkan penggunaanyaapllikasi nya lancar ya kepuasan bertransaksi disinimenurut aplikasi bagus sempurna banget ya tinggal ditambah menu pelengkap utc memudahkan aplikasi nya jaringan jlk': "the convenience of the cellphone application, yes, the application is useful, satisfaction, the features are complete, it makes it easy to use, the application is smooth, yes, the satisfaction of making transactions here, according to the application, it's really perfect, yes, just add a complementary menu, UTC makes the application easier, jlk network",
 'untung akun ovo hack terima kasih': 'Luckily the OVO account was hacked, thank you',
 'akongz bagus transaksi nya gratis': 'akongz is good, the transactions are free',
 'cepet pelayanan': 'fast service',
 'serba mudahhanya rumah': 'everything is easy, just the house',
 'kemudahan bertransakti bunga cair': 'ease of transacting liquid interest',
 'coba': 'try',
 'aplikasi nya bagus banget yasimpel mudah pastinya kemudahan pengguna nyaselain manfaat dapatkan mudah membeli pulsabayar tagihan listrik manfaat aplikasi bagus nya aplikasi nya dilengkapi fitur fitur lengkap memudahkan aplikasi nya bertransaksi ya kawan': "the application is really good, it's simple, easy, of course it's easy for users, apart from the benefits of getting it, it's easy to buy credit, pay electricity bills, the benefits of the application are good, the application is equipped with complete features, the application makes transactions easy, friends",
 'bantuan admin laporin transaksi palsu akun kena blokir mbanking ga': 'Admin help report fake transactions, your account has been blocked by mbanking or not',
 'yaaa': 'yeah',
 'nyaman': 'comfortable',
 'prose cepat': 'fast process',
 'prose nya cepat': 'the process is fast',
 'okelah': 'Okay',
 'bermanfaatapky enak gak ribet': 'useful, delicious, not complicated',
 'membantu ya semoga kedepan kendala': 'It helps, hopefully there will be problems in the future',
 'bank digital termudah': 'Easiest digital bank',
 'bagus kenyamanan transaksi didalamnya salah satunya salah aplikasi terbaik dikelasnya bagus detail komponen yg terkandung didalamnya pemakaian amanah terpercaya sia sia udah menabung suku bunga tambahan fitur terbaru yg keren update mantap frendddd': "good transaction convenience in it, one of the best applications in its class, good details of the components contained in it, use of trusted trusts, it's useless to save, additional interest rates, cool new features, great updates, frendddd",
 'good aplikasion': 'good application',
 'bagus banget': 'really good',
 'pake bintang ya': 'Use stars',
 'happy': 'happy',
 'bebas admin transaksi': 'admin free transactions',
 'nice': 'nice',
 'kecewa aplikasi seabanksaya login kluar trus login tertulis nik digunakansaya login modelnya kaya disuruh daftarsekali bilang login mw daftar': 'Disappointed with the Seabank application, I logged in, it exited, then login said Nik was used. I logged in, the model was like I was told to register, once it said login, I registered.',
 'transaksi simpel': 'simple transaction',
 'senang': 'like',
 'cakepp tf': 'cakepp tf',
 'praktis hemat biaya': 'practically cost-effective',
 'aplikasi yg membantu bermanfaat pembisnis yg pembelian barang via transfer penjualan barang diseluruh indonesia ayok kembangkan aplikasi sejagat raya indonesia terima kasih': "an application that helps, useful for business people who purchase goods via transfer, sell goods throughout Indonesia, let's develop an application throughout Indonesia, thank you",
 'joss': 'joss',
 'buruk': 'bad',
 'baguspelayanan cepat transfer kemanapun gratis biaya ribet pertahanan': 'good service, fast transfers anywhere, free of hassle of defense costs',
 'menarik serbaguna makasih seebank': 'Interesting, versatile, thanks Seabank',
 'bagus nyooo': "that's good noooo",
 'bagus aplikasi nta': 'really good application',
 'secepat kilat': 'lightning fast',
 'alkhamdulillahberkah berkah berkahsemoga aplikasi mengutamakan pelanggan mengutamakan keamanan kenyamananaamiin': 'Alkhamdulillah, blessings, blessings, blessings, hopefully the application prioritizes customers, prioritizing security, comfort, amen',
 'kekurangan nya gak tarik tunai': 'the disadvantage is that it does not withdraw cash',
 'memudahkan transaksi': 'make transactions easier',
 'membantu cepat': 'help fast',
 'sistem yg': 'system which',
 'ok': 'ok',
 'semoga maju sukses': 'good luck moving forward',
 'habis tf k notifikasi masuk uangnya ga masuk beranda suruh menghubungi bantuan udh jam ga jwban butuh bgt': "After TF, the notification came in, the money didn't arrive, the homepage told me to call for help, after hours, no answer, I really need it",
 'trf shoppe wallet': 'trf shoppe wallet',
 'mantappppp': 'cool',
 'aplikasi tololl aplikasi gagal tolong hati² penipuan plis coba² mending menyesal kasih ulasan gaada korban lainya ok': "Tololl application failed, please be careful of fraud, please try, it's better to regret giving a review, there are no other victims, OK",
 'memudahkan': 'facilitate',
 'bagusss free tf kemna sja': 'Nice, free TF anywhere',
 'membantu bermanfaat': 'helpful helpful',
 'ui tolong ubah': 'ui please change it',
 'bagus memuaskan memudahkan transaksi': 'good, satisfying, makes transactions easy',
 'nyaman bnget makenya kuota gratis transfer admin': "It's really convenient because the quota is free for admin transfers",
 'mantep': 'steady',
 'enak gratis tf kemana aja': 'nice free tf anywhere',
 'alhamdulillah semoga aman': "thank God, hopefully it's safe",
 'mudah': 'easy',
 'update ga masuk gimana sih jaringan buka aplikasi laen lancar jaya': "the update doesn't go in, how can the network open the laen application smoothly?",
 'apk yg bermanfaat recomend': 'useful apk recommend',
 'mencoba semoga lancar jujur terpercaya mudah menanggapi komentar pengguna': 'try to be smooth, honest, reliable, easy to respond to user comments',
 'kerren': 'last',
 'bagus membantu': 'good help',
 'gimana ya daftar sulit foto muka gagal pdhl notif eror': 'How come the difficult list of face photos failed even though the notification was an error?',
 'oke mantap': 'okay great',
 'okehhh bangetttt senang pake': 'okay, really happy to use it',
 'bagus sea bank gratis transfer bank lokas gratis transfer e walletehskrg udh aja kayak bank laintf beda bank e wallet udh kena cassama aja dgn bank lainkalau kembalikan kebijakan nya kayak gratis bank e wallet': "good sea bank free local bank transfers free e wallet transfers now it's just like other banks but different e wallet banks just have to be cassed with other banks if you return the policy is like free bank e wallet",
 'manttapp bgt da playanan nya smga sukses slalu senang pke playanan nya jg ramah': 'The service is really great and good luck. Always happy with the friendly service',
 'csnya ramah': 'CS is friendly',
 'seruuu gatau berasa seneng aja terhubung sm shopee': "I'm so excited to be connected to shopee sm",
 'mudah banget pengoperasiannya': 'very easy to operate',
 'enak banget': 'very tasty',
 'pokoknya terbaik': 'basically the best',
 'suka aplikasi nya yg ngegunainnya kaya bingung kalo naro duit d apk nya tbtb tarik tarik tunai ny dimana kdng d pindahan dlu rekening d tarik': "I like the application that uses it, I'm confused if I want money in the apk, I can't pull it, pull it, cash it, where it's transferred to the account, pull it",
 'cepat': 'fast',
 'membantumenggunakan nya jg mudahstiap transaksi nya gratis pulasangat puas': "It helps to use it easily, every transaction is free and I'm very satisfied",
 'lancar mudah transaksi ya berkat aplikasi iniselain memiliki fiturfitur komplit aplikasi canggih ya memudahkan transaksi ya kawandimasa membutuhkan aplikasi membantu aplikasi iniluar kepuasan kemudahan pengguna nyapas banget transaksi ponsel': "smooth, easy transactions, thanks to this application, apart from having complete features, a sophisticated application, it makes transactions easy, friends, when you need an application, this application is beyond satisfaction, the user's ease really makes cellphone transactions easy",
 'gak login periksa koneksi internet normal internet': 'not logged in, check the internet connection is normal',
 'pengguna bagus paten paten x': 'good user patent patent x',
 'buka rekening dah berminggu ga selesai nunggu notif': "Opened an account, I haven't finished waiting for a notification for weeks",
 'jelek narik saldo aplikasi eror sistem sibuk butuh uangnya': 'Badly withdrawing balance, application error, system busy, need the money',
 'mudah penggunaannya ga pake ribet': 'easy to use without any hassle',
 'memuaskan': 'satisfying',
 'good jobb': 'good',
 'ribet worth it karna biaya admin love bgt flipp': 'the hassle is worth it because of the admin fees, really love Flipp',
 'mantull': 'mantull',
 'aplikasi bagus mengatur pengeluaran memiliki fitur pengelolaan keuangan membantu menabung praktis dibandingkan mendaftar bank digital coba rekomended transaksi aplikasi nyaman cepat alhamdulilah kendala transaksi update tambahkan fitur pengguna bosan aplikasi': 'good application for managing expenses, has financial management features, helps save, practical compared to registering with a digital bank, try recommended application transactions, convenient, fast, thank God, transaction problems, updates add features, users are bored with the application',
 'suka banget transfer pake mantab': 'really like the transfer using Mantab',
 'mantap transaksi nyatapi sayangkan voucernya rb': 'great transaction, but unfortunately the voucher is Rp',
 'menyenangkan transaksi': 'pleasant transaction',
 'alhamdulillah coba terbaiksmoga': 'Thank God, try your best, hopefully',
 'gampang cepat gratis': 'easy fast free',
 'puas': 'damage',
 'mntp daptar': 'mintp list',
 'lmyn kirim rek free biaya nya semoga berlanjut': 'lmyn send a free account, hopefully it will continue',
 'the best': 'the best',
 'bermanfaat': 'beneficial',
 'transaksi nya cepat aman': 'the transaction is fast and safe',
 'lancar': 'fluent',
 'transaksi shopee bayar pakai pesanan bayar saldo terpotong statusnya terbayar batalin saldo refund komplain suruh tunggu kejelasan saldo terpotong': 'Shopee transactions pay using orders, pay the balance deducted, the status is paid, cancel the balance, refund, complaint, order to wait for clarity on the balance deducted',
 'top up kaspro tanggal sampe sekrng terkirim duit nya padhal riwayat aplikasi udah sukses coba top up aplikasi eh ngga tunggu detik udah nambah saldo kaspro nya sanggat kecewa ama ni aplikasi': "top up kaspro date until as soon as the money is sent, the history of the application has been successful, try to top up the application, don't wait for the moment to increase the kaspro balance, I am very disappointed with this application",
 'terima kasih merespon penangannya': 'thank you for responding to the handler',
 'perfect': 'perfect',
 'nomor aktp susah login disuruh ngehubungi no aktp aneh': 'Aktp number is difficult to log in, told to call strange Aktp number',
 'sea bank oke bgt': 'Sea Bank is really good',
 'diakui aplikasi memiliki manfaat ya nyaman bertransaksi kawanaplikasi nya ringan ngga ribet penggunaan nyamenurut aplikasi bagus ya tinggal ditambah menu pelengkap biar sempurna utc memudahkan aplikasi nya jaringan stabil yafitur fitur nya lengkap komplit ya': "It is recognized that the application has benefits, yes, it's comfortable to make transactions, friends, the application is light, it's not complicated to use, according to the application, it's good, just add a complementary menu to make it perfect, UTC makes the application easier, the network is stable, yes, the features are complete, yes.",
 'mudah semoga aman': 'easy, hopefully safe',
 'biaya admin murah': 'cheap admin fees',
 'mantap transaksi dikenakan biaya': 'However, transactions are subject to fees',
 'membantu transaksi': 'assist with transactions',
 'mantaaab sea bank': 'Mantalab C Bank',
 'bagus apk praktis': 'nice practical apk',
 'memuaskankarena transfer bank biaya tambahan': 'satisfactory because bank transfers are additional fees',
 'alhamdulillah sdh pakai': 'Thank God I have used it',
 'mantap berkualitas mumpuni': 'solid, good quality',
 'membantu terimakasih': 'help thank you',
 'c cuancuan n cuan': 'c how much n how',
 'snagat nyaman': 'very comfortable',
 'is the best': 'is the best',
 'mudah gampang transfer kemana aja gratis biaya kirim bagus sih': 'easy, easy transfer anywhere, free shipping, great',
 'mudah nyaman terpercaya': 'easy comfortable reliable',
 'set': 'set',
 'layanan sangatt': 'very good service',
 'sangan membantu': 'very helpful',
 'bermanfaat trimaksih': 'useful thanks',
 'sibang deposito palas': 'sibang palas deposit',
 'mudah membantu': 'easy to help',
 'ok siip': 'OK, great',
 'prose cepat amanah': 'Fast and reliable process',
 'serba cepat pokoknya the best': 'Fast is the best',
 'goodlah': 'goodlah',
 'ok d bgus': 'ok d bgus',
 'bagus banget investasi': 'really good investment',
 'mantap dah pokonya': "It's good, that's all",
 'mantap bagus': 'great, good',
 'love': 'love',
 'bagus berkualitas': 'good quality',
 'membantu apapun pendapat bunga ya membantu': 'Help, whatever your opinion is, yes it helps',
 'transfernya cepat': 'the transfer is fast',
 'aplikasi e bank termantao mantapppp transfer rekening ovo gratissss x': 'The most reliable e-bank application for free OVO account transfers x',
 'good job': 'good job',
 'efesien transfer gratis': 'efficient free transfer',
 'membantu bagus banget pelayanannya kalo kartu debit flazz nya bagus sih': 'the service is really good if the flazz debit card is good',
 'mudah gk ribet': 'easy, not complicated',
 'suka menabung sea bank tranfer gratis admin': 'like saving seabank free transfer admin',
 'goodluck': 'goodluck',
 'maju trus': 'move on then',
 'memuaskan terimakasih': 'satisfying thank you',
 'sagat puas': 'very satisfied',
 'semoga maju tingkatkan ya kinerja nyatq': 'Hopefully progress will increase real work power',
 'mudah nyaman berbunga gak lumayan': 'easy comfortable flowering not bad',
 'mudah cepat dg bi fast free biaya transfer': 'easy fast and bi fast free transfer fees',
 'gimana sih saldo nerima transaksi pengirim berhasil saldo tetep kosong gimana terusan saldo yg transfer blum masuk': 'How does the balance receive a successful delivery transaction? The balance remains empty. How is the transfer balance not yet received?',
 'terbaik': 'the best',
 'aplikasinya bagus mudah': 'the application is good and easy',
 'transaksi cepat cuman utk pinjaman msh blm': 'Fast transactions, only for loans yet',
 'membantu kebutuhan financial': 'help with financial needs',
 'mantaaap mudah': 'really easy',
 'bank digital serba belanja shopee transfer gratis bunga ga biaya admin bulanan bagus bgtlah': 'All-in-one digital bank for shopee shopping, interest free transfers, no monthly admin fees, really good',
 'free biaya transfer all rek kuotabulan': 'Free transfer fees for all monthly quota accounts',
 'mempermudahkan': 'simplify',
 'bagus semoga sukses': 'good, good luck',
 'lumayan baguss apk nya membantu transaksi ewalet bank': 'The apk is pretty good for helping bank e-wallet transactions',
 'sat set gak ribet bunganya gede suka': 'the set is not complicated, the flowers are big, I like it',
 'bank terbaik yg': 'the best bank',
 'gratis tf nyaa banyakk membantu': 'The free TF helps a lot',
 'opsional': 'optional',
 'mudah penggunaannya membantu': 'ease of use helps',
 'setia transfer uangalasan nyakarena aplikasi nya update promo terbaru terkiniisi fitur nya lengkap bagus keamanan nya terpercayakalau cuman membosankan aplikasi menghasilkan uang ajak teman kelebihan aplikasi inisecara aplikasi nya rekomendasi banget kawankawan': "loyal to transfer money, the reason is because the application is updated with the latest promos, the features are complete, good, the security is reliable, if it's just boring, the application makes money, invite friends. The advantages of this application are that the application is really recommended, friends.",
 'mudah ktimbang dana msh bingung krna pemula': "It's easy to compare funds but you're still confused because you're a beginner",
 'mantab guy': 'mantab guy',
 'gratis smua bank thx': 'free for all banks thx',
 'sukaaak bangeeet gratis admin gratis biaya transfer kemanapun semoga yaa amiiin': 'really like it, free admin, free transfer fees anywhere, hopefully, amen',
 'min gak adain fitur cetak langsung ukuran kertas lebar mm memudahkan cetak bukti transfer': 'Min, there is no direct print feature, the paper size is mm wide, making it easier to print transfer proof',
 'wow amazing': 'wow amazing',
 'bagus gakribet': 'good, not complicated',
 'mudah terbaik': 'easy best',
 'mudah cepat murah': 'easy fast cheap',
 'krm mami': 'thanks to mom',
 'nyaman mudah senang seebank': 'comfortable easy happy seabank',
 'mengalami kadaluarsa nomor hp login disuruh input kode otp mengubungi c dihubungi ya': 'If your cell phone number has expired, you are asked to enter the OTP code. Contact C. Call me',

In [ ]:
data.replace(translations, inplace = True)
data

                                                content
0                                                    in
1                                                   top
2     application for children with visual disabilities
3                                                 solid
4     The best user satisfaction, apart from the ben...
...                                                 ...
3479                                        simple free
3480                      No problem is easy, it's easy
3481                         fast accurate transactions
3482  Fast service, not inferior to HTI liquid inter...
3483                          Min deposit interest rate

[3484 rows x 1 columns]

In [ ]:
data.to_excel('/content/drive/MyDrive/DataFix/Label/SastSeabank_DataTranslated.xlsx', index=False)

# Memisahkan Data Menjadi Set Train (Pelatihan) dan Set Test (Pengujian)

In [ ]:
#SPLIT DATA
import pandas as pd

dataset = pd.read_excel('/content/drive/MyDrive/DataFix/Label/SastSeabank_DataTranslated.xlsx')

# Hitung jumlah baris dalam dataset
num_rows = len(dataset)

# Hitung jumlah baris yang akan digunakan sebagai pelatihan (disini 50%)
train_size = int(0.5 * num_rows)

# Bagi dataset menjadi subset pelatihan dan pengujian
train_data = dataset[:train_size]
test_data = dataset[train_size:]

# Simpan subset pelatihan ke dalam file xlsx
train_data.to_excel('/content/drive/MyDrive/DataFix/Label/SastSeabank_DataTrainEnglish.xlsx', index=False)

# Simpan subset pengujian ke dalam file xlsx
test_data.to_excel('/content/drive/MyDrive/DataFix/Label/SastSeabank_DataTestEnglish.xlsx', index=False)

In [ ]:
!pip install Textblob

Requirement already satisfied: Textblob in /usr/local/lib/python3.10/dist-packages (0.17.1)
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.10/dist-packages (from Textblob) (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->Textblob) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->Textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->Textblob) (2024.5.15)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->Textblob) (4.66.4)

In [ ]:
from textblob import TextBlob

In [ ]:
train_data

                                                content
0                                                    in
1                                                   top
2     application for children with visual disabilities
3                                                 solid
4     The best user satisfaction, apart from the ben...
...                                                 ...
1737                                the process is fast
1738           Send it wherever it's easy and it's free
1739                                     fast responsif
1740                                          great cut
1741                                          satisfied

[1742 rows x 1 columns]

# Analisis Sentimen pada Data Train (Pelatihan)

In [ ]:
data_content = list(train_data['content'])
polaritas = 0

status = []
total_positif = total_negatif = total = 0

for i, tweet in enumerate(data_content):
    analysis = TextBlob(tweet)
    polaritas += analysis.polarity

    if analysis.sentiment.polarity > 0.0:
        total_positif += 1
        status.append('Positif')
    else:
        total_negatif += 1
        status.append('Negatif')

    total += 1

print(f'Hasil Analisis Data:\nPositif = {total_positif}\nNegatif = {total_negatif}')
print(f'\nTotal Data : {total}')

Hasil Analisis Data:
Positif = 1182
Negatif = 560

Total Data : 1742

In [ ]:
status = pd.DataFrame({'Label': status})
train_data['Label'] = status
train_data

<ipython-input-17-ddb1f5b9bf00>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data['Label'] = status

                                                content    Label
0                                                    in  Negatif
1                                                   top  Positif
2     application for children with visual disabilities  Negatif
3                                                 solid  Negatif
4     The best user satisfaction, apart from the ben...  Positif
...                                                 ...      ...
1737                                the process is fast  Positif
1738           Send it wherever it's easy and it's free  Positif
1739                                     fast responsif  Positif
1740                                          great cut  Positif
1741                                          satisfied  Positif

[1742 rows x 2 columns]

# Menyeimbangkan Data (Balancing Data)

In [ ]:
# Memisahkan data berdasarkan label
positif_data = train_data[train_data['Label'] == 'Positif']
negatif_data = train_data[train_data['Label'] == 'Negatif']

In [ ]:
# Menentukan jumlah sampel minimum di 2 kelas kelas
min_samples = min(total_positif, total_negatif)

In [ ]:
from sklearn.utils import resample

In [ ]:
# Melakukan penyeimbangan data dengan undersampling
positif_data_resampled = resample(positif_data, replace=False, n_samples=min_samples, random_state=42)
negatif_data_resampled = resample(negatif_data, replace=False, n_samples=min_samples, random_state=42)

In [ ]:
# Menggabungkan kembali data yang telah disusun ulang
balanced_data = pd.concat([positif_data_resampled, negatif_data_resampled])

In [ ]:
data_content_balanced = list(balanced_data['content'])
polaritas_balanced = 0

status_balanced = []
total_positif_balanced = total_negatif_balanced = total_balanced = 0

for i, tweet in enumerate(data_content_balanced):
    analysis = TextBlob(tweet)
    polaritas_balanced += analysis.polarity

    if analysis.sentiment.polarity > 0.0:
        total_positif_balanced += 1
        status_balanced.append('Positif')
    else:
        total_negatif_balanced += 1
        status_balanced.append('Negatif')

    total_balanced += 1

print(f'Hasil Analisis Data Setelah Penyeimbangan:\nPositif = {total_positif_balanced}\nNegatif = {total_negatif_balanced}')
print(f'\nTotal Data Setelah Penyeimbangan: {total_balanced}')

Hasil Analisis Data Setelah Penyeimbangan:
Positif = 560
Negatif = 560

Total Data Setelah Penyeimbangan: 1120

In [ ]:
train_data.to_excel('/content/drive/MyDrive/DataFix/Label/SastSeabank_DataTrainEngLabeled.xlsx',index=False)

In [ ]:
balanced_data.to_excel('/content/drive/MyDrive/DataFix/Label/SastSeabank_DataTrainEngLabeledBalanced.xlsx', index=False)

# Menerjemahkan Data yang Telah Diseimbangkan ke Dalam Bahasa Indonesia

In [ ]:
import pandas as pd
from googletrans import Translator

def translate_to_indonesian(text):
    translator = Translator()
    result = translator.translate(text, src='en', dest='id')
    return result.text

def translate_excel_column(input_file, output_file, sheet_name, column_name):
    df = pd.read_excel(input_file, sheet_name=sheet_name)
    df[column_name] = df[column_name].apply(translate_to_indonesian)

    with pd.ExcelWriter(output_file) as writer:
        df.to_excel(writer, index=False, sheet_name=sheet_name)
    print("Translation complete. Translated data saved to a new Excel file!")

# Example usage
input_file = '/content/drive/MyDrive/DataFix/Label/SastSeabank_DataTrainEngLabeledBalanced.xlsx'
output_file = '/content/drive/MyDrive/DataFix/Label/SastSeabank_DataTrainIndLabeledBalanced.xlsx'
sheet_name = 'Sheet1'  # Change to your sheet name
column_name = 'content'  # Change to the name of the column you want to translate

translate_excel_column(input_file, output_file, sheet_name, column_name)

Translation complete. Translated data saved to a new Excel file!

In [ ]:
import pandas as pd
from googletrans import Translator

def translate_to_indonesian(text):
    translator = Translator()
    result = translator.translate(text, src='en', dest='id')
    return result.text

def translate_excel_column(input_file, output_file, sheet_name, column_name):
    df = pd.read_excel(input_file, sheet_name=sheet_name)
    df[column_name] = df[column_name].apply(translate_to_indonesian)

    with pd.ExcelWriter(output_file) as writer:
        df.to_excel(writer, index=False, sheet_name=sheet_name)
    print("Translation complete. Translated data saved to a new Excel file!")

# Example usage
input_file = '/content/drive/MyDrive/DataFix/Label/SastSeabank_DataTestEnglish.xlsx'
output_file = '/content/drive/MyDrive/DataFix/Label/SastSeabank_DataTestIndo.xlsx'
sheet_name = 'Sheet1'  # Change to your sheet name
column_name = 'content'  # Change to the name of the column you want to translate

translate_excel_column(input_file, output_file, sheet_name, column_name)

Translation complete. Translated data saved to a new Excel file!